language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: 
- "mvn test"